/* LifeSim v23 — Memory, Consequence, World & Dynasty layer */
(function(){
  'use strict';
  const VERSION='v23';
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,Number(v)||0));
  const rand=(min,max)=>Math.floor(Math.random()*(max-min+1))+min;
  const pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const cap=s=>String(s||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
  const money=n=>{try{return typeof fmtFull==='function'?fmtFull(n):typeof fmt==='function'?fmt(n):'$'+Math.round(n||0).toLocaleString('en-US');}catch(_){return '$'+Math.round(n||0).toLocaleString('en-US');}};
  const net=G=>{try{return typeof netWorth==='function'?netWorth(G):(G?.money||0);}catch(_){return G?.money||0;}};
  const safeApply=(G,e)=>{if(!G||!e)return; try{ if(typeof applyEffect==='function')applyEffect(G,e); else if(typeof applyStats==='function')applyStats(G,e); else Object.entries(e).forEach(([k,v])=>{if(typeof v==='number')G[k]=(Number(G[k])||0)+v;}); }catch(err){console.warn('v23 apply failed',err);} };

  const DATA={
    dna:['risk','discipline','empathy','ambition','luck','creativity','loyalty','impulse'],
    fate:[
      {id:'late_bloomer',icon:'🌙',name:'Late Bloomer',trigger:G=>G.age>=31&&!G.v23.fateRevealed?.late_bloomer,e:{happiness:6,smarts:4,reputation:3},text:'Something finally clicked. You are not behind — your life just had a slower ignition.'},
      {id:'golden_opportunity',icon:'✨',name:'Golden Opportunity',trigger:G=>G.age>=18&&(G.v23.world?.tech||50)>72&&!G.v23.fateRevealed?.golden_opportunity,e:{money:rand(3500,18000),fame:4,stress:3},text:'A rare opportunity appeared because the world changed at exactly the right time.'},
      {id:'family_curse',icon:'🕯️',name:'Family Curse',trigger:G=>G.age>=25&&(G.v23.reputation?.family||50)<32&&!G.v23.fateRevealed?.family_curse,e:{happiness:-5,stress:7},text:'Old family patterns resurfaced. Some battles began before you were born.'},
      {id:'dangerous_charisma',icon:'🦊',name:'Dangerous Charisma',trigger:G=>G.age>=18&&(G.looks||0)>70&&!G.v23.fateRevealed?.dangerous_charisma,e:{fame:5,karma:-2},text:'People listened when you spoke. That power can heal, manipulate, or destroy.'},
      {id:'health_fragility',icon:'🩺',name:'Health Fragility',trigger:G=>G.age>=38&&(G.health||0)<45&&!G.v23.fateRevealed?.health_fragility,e:{health:-2,stress:4},text:'Your body started demanding respect. Ignoring it is no longer free.'},
      {id:'born_leader',icon:'🦁',name:'Born Leader',trigger:G=>G.age>=21&&(G.reputation||50)>70&&!G.v23.fateRevealed?.born_leader,e:{reputation:6,fame:4,stress:3},text:'People started looking to you when things became uncertain.'},
      {id:'tragic_romance',icon:'🥀',name:'Tragic Romance',trigger:G=>G.age>=18&&G.rels?.partner&&(G.rels.partner.love||50)<35&&!G.v23.fateRevealed?.tragic_romance,e:{happiness:-7,smarts:3},text:'Love taught you something painful, but permanent.'},
      {id:'lucky_investor',icon:'📈',name:'Lucky Investor',trigger:G=>G.age>=18&&(G.v23.world?.economy||50)>68&&!G.v23.fateRevealed?.lucky_investor,e:{money:rand(1500,12000),smarts:2},text:'You caught the market mood before most people understood what was happening.'}
    ],
    moods:[
      ['peaceful',G=>(G.stress||0)<25&&(G.happiness||0)>62],['burned out',G=>(G.stress||0)>72],['lonely',G=>!G.rels?.partner&&(G.rels?.friends||[]).length<2&&G.age>16],['inspired',G=>(G.smarts||0)>72&&(G.happiness||0)>55],['guilty',G=>(G.karma||0)<-20],['powerful',G=>(G.fame||0)>65||(G.reputation||0)>78],['lost',G=>G.age>22&&!G.career&&(G.happiness||0)<50],['motivated',G=>(G.v23?.dna?.ambition||50)>70&&(G.stress||0)<75]
    ],
    rivalRoles:['school rival','career rival','business rival','romantic rival','sports rival','creative rival','criminal rival'],
    secrets:[
      {id:'hidden_debt',icon:'💸',name:'Hidden Debt',risk:'financial',e:{money:-2500,stress:6,reputation:-1}},
      {id:'fake_story',icon:'🎭',name:'Fake Story',risk:'public',e:{fame:-5,reputation:-8,stress:5}},
      {id:'betrayed_friend',icon:'🧊',name:'Betrayed Friend',risk:'relationship',e:{happiness:-5,karma:-4,stress:4}},
      {id:'stolen_cash',icon:'🕶️',name:'Stolen Cash',risk:'crime',e:{money:1800,karma:-8,stress:8}},
      {id:'secret_donation',icon:'🤲',name:'Secret Donation',risk:'good',e:{karma:8,happiness:4,money:-800}}
    ],
    reputationKeys:[['family','Family'],['career','Career'],['public','Public'],['romantic','Romance'],['criminal','Criminal'],['business','Business'],['online','Online']],
    moralAxes:[['selfless','Selfish','Selfless'],['risk','Safe','Risky'],['honest','Manipulative','Honest'],['responsible','Free','Responsible']],
    ambitionChapters:['The Spark','First Sacrifice','Public Test','Crisis Point','Legacy Proof']
  };

  const State={
    ensure(G=window.G){
      if(!G)return null;
      G.v23=G.v23||{};
      const v=G.v23;
      if(!Array.isArray(v.memories))v.memories=[];
      if(!v.tags)v.tags={};
      if(!v.relationMemory)v.relationMemory={};
      if(!v.reputation)v.reputation={family:50,career:50,public:50,romantic:50,criminal:0,business:50,online:50};
      if(!v.moral)v.moral={selfless:50,risk:50,honest:50,responsible:50};
      if(!v.dna){v.dna={};DATA.dna.forEach(k=>v.dna[k]=rand(28,82)); this.biasDNA(G);}
      if(!Array.isArray(v.fateCards)||!v.fateCards.length)v.fateCards=this.pickFates(3);
      if(!v.fateRevealed)v.fateRevealed={};
      if(!Array.isArray(v.newspapers))v.newspapers=[];
      if(!v.world)v.world=this.newWorld(G);
      if(!Array.isArray(v.rivals))v.rivals=[];
      if(!Array.isArray(v.secrets))v.secrets=[];
      if(!v.familyTree)v.familyTree={surname:G.surname||'',founder:`${G.name||''} ${G.surname||''}`.trim(),members:[],heirs:[],legacyScore:0};
      if(!v.ambitionArc)v.ambitionArc={chapter:0,chapterName:DATA.ambitionChapters[0],score:0,history:[]};
      if(!v.codexFilter)v.codexFilter='memories';
      this.ensureFamilyTree(G);
      this.ensureRelations(G);
      this.mentalState(G);
      return v;
    },
    biasDNA(G){const d=G.v23.dna,t=G.trait; if(!d)return; const b=(k,n)=>d[k]=clamp((d[k]||50)+n,0,100);
      if(t==='ambitious'||t==='visionary')b('ambition',14); if(t==='disciplined'||t==='stoic')b('discipline',14); if(t==='empath'||t==='honest')b('empathy',12),b('loyalty',10); if(t==='lucky')b('luck',16); if(t==='creative'||t==='curious')b('creativity',16); if(t==='maverick'||t==='arrogant')b('risk',14),b('impulse',10); if(t==='lazy')b('discipline',-14),b('impulse',7);
    },
    pickFates(n){const pool=[...DATA.fate]; const out=[]; while(pool.length&&out.length<n){const f=pool.splice(Math.floor(Math.random()*pool.length),1)[0]; out.push({id:f.id,icon:f.icon,name:f.name,revealed:false});} return out;},
    newWorld(G){const c=G.country||{}; return {year:G.year||2026,economy:rand(38,72),housing:rand(36,74),crime:rand(24,68),tech:rand(34,78),healthcare:clamp((c.lifeExp||78)-30,30,88),inflation:rand(18,62),jobMarket:rand(36,74),socialMood:rand(36,75),politics:rand(24,76),warRisk:rand(4,42),lastHeadlineAge:-99};},
    ensureFamilyTree(G){const tree=G.v23.familyTree; const add=(p,role)=>{if(!p)return; const name=`${p.name||''} ${p.surname||G.surname||''}`.trim(); if(!name||tree.members.some(m=>m.name===name&&m.role===role))return; tree.members.push({name,role,age:p.age||0,alive:p.alive!==false,relation:p.role||role});}; add({name:G.name,surname:G.surname,age:G.age,alive:G.alive},'founder'); add(G.rels?.father,'father'); add(G.rels?.mother,'mother'); (G.rels?.siblings||[]).forEach(x=>add(x,'sibling')); (G.rels?.children||[]).forEach(x=>{add(x,'child'); if(!tree.heirs.some(h=>h.name===x.name))tree.heirs.push({name:x.name,age:x.age||0,trait:x.personality||pick(['Curious','Bold','Kind','Rebellious','Calm']),dream:x.dream||pick(['music','business','science','sport','family'])});}); tree.legacyScore=this.legacyScore(G);},
    ensureRelations(G){const ensurePerson=(p,role)=>{if(!p||!p.name)return; const key=this.personKey(p,role); const rm=G.v23.relationMemory[key]||(G.v23.relationMemory[key]={name:p.name,role:role||p.role||'person',trust:clamp(p.trust??p.love??55),respect:clamp(p.respect??50),jealousy:clamp(p.jealousy??rand(8,32)),personality:p.personality||pick(['warm','guarded','ambitious','sensitive','funny','proud','loyal']),history:[],currentProblem:''}); rm.love=clamp(p.love??rm.love??50); rm.age=p.age||rm.age||0; if(!rm.currentProblem&&Math.random()<.06)rm.currentProblem=pick(['feels ignored','wants more honesty','worries about money','needs your support','is proud but distant']); return rm;}; ensurePerson(G.rels?.partner,'partner'); ensurePerson(G.rels?.father,'father'); ensurePerson(G.rels?.mother,'mother'); (G.rels?.friends||[]).slice(0,8).forEach(p=>ensurePerson(p,'friend')); (G.rels?.children||[]).slice(0,12).forEach(p=>ensurePerson(p,'child'));},
    personKey(p,role){return `${role||p.role||'person'}:${p.id||p.name||'unknown'}:${p.surname||''}`.toLowerCase();},
    mentalState(G){const found=DATA.moods.find(([,fn])=>{try{return fn(G);}catch(_){return false;}}); const label=found?found[0]:'steady'; const v=G.v23; if(v.mentalState!==label){v.lastMentalState=v.mentalState; v.mentalState=label;} return label;},
    legacyScore(G){const v=G.v23||{}; return Math.round(Math.max(0,Math.min(999,(G.age||0)*1.5+(G.reputation||50)*1.2+(G.karma||0)*.6+Math.min(220,net(G)/12000)+(G.fame||0)*1.1+(G.rels?.children||[]).length*18+(v.memories||[]).filter(m=>m.weight>=4).length*12)));}
  };

  const Memory={
    add(G,id,label,text,category='life',weight=2,extra={}){const v=State.ensure(G); if(!v)return null; const key=id||String(label||text||Date.now()).toLowerCase().replace(/[^a-z0-9]+/g,'_').slice(0,80); if(v.tags[key]&&!extra.repeat)return null; const item={id:key,label:label||cap(key),text:text||label||key,category,weight,age:G.age||0,year:G.year||'',ts:Date.now(),...extra}; v.memories.unshift(item); v.memories=v.memories.slice(0,140); v.tags[key]=true; if(window.LifeSimV22?.TimelinePlus?.capture)try{LifeSimV22.TimelinePlus.capture(`${item.label}: ${item.text}`,category);}catch(_){ } return item;},
    relation(G,person,kind,text,delta={}){const v=State.ensure(G); if(!v||!person)return; const key=State.personKey(person,person.role||kind); const rm=v.relationMemory[key]||(v.relationMemory[key]={name:person.name||'Someone',role:person.role||kind||'person',trust:50,respect:50,jealousy:20,history:[]}); Object.entries(delta).forEach(([k,n])=>rm[k]=clamp((rm[k]||0)+n,0,100)); rm.history.unshift({age:G.age||0,kind,text}); rm.history=rm.history.slice(0,12); if(text)Memory.add(G,`rel_${key}_${kind}_${G.age}`,`${rm.name} remembers`,text,'relationship',3,{repeat:true});},
    inferFromLog(G,raw,type){const text=String(raw||''); if(!text||text.length<3)return; const low=text.toLowerCase();
      if((G?.age||0)===0&&/personal goals generated|local economy|family has .*set aside|reserved for adulthood|was born|born into|father:|mother:|sibling:|trait:|future ambition/.test(low))return;
      if(/born|began life/.test(low))this.add(G,'birth_origin','Origin Story',text,'identity',4);
      if(/graduat|degree|university|school/.test(low))this.add(G,`education_${G.age}`,'Education Milestone',text,'career',3);
      if(/hired|job|career|promot|raise|ceo|surgeon|judge/.test(low))this.add(G,`career_${G.age}_${low.slice(0,12)}`,'Career Memory',text,'career',3,{repeat:true}),Reputation.shift(G,'career',3);
      if(/married|partner|crush|kiss|date|love/.test(low)){this.add(G,`love_${G.age}_${low.slice(0,12)}`,'Love Memory',text,'love',3,{repeat:true}); if(G.rels?.partner)this.relation(G,G.rels.partner,'love',text,{trust:2,respect:1}); Reputation.shift(G,'romantic',2);}
      if(/child|baby|son|daughter|pregnan/.test(low)){this.add(G,`family_${G.age}_${low.slice(0,12)}`,'Family Memory',text,'family',5,{repeat:true}); Reputation.shift(G,'family',4);}
      if(/prison|crime|stole|robbery|arrest|gang/.test(low)){this.add(G,`crime_${G.age}_${low.slice(0,12)}`,'Shadow Memory',text,'crime',4,{repeat:true}); Reputation.shift(G,'criminal',5); Reputation.shift(G,'public',-3); Moral.shift(G,{honest:-4,risk:4,responsible:-3});}
      if(/business|company|startup|founded/.test(low)){this.add(G,`business_${G.age}_${low.slice(0,12)}`,'Business Memory',text,'business',4,{repeat:true}); Reputation.shift(G,'business',4);}
      if(/hospital|illness|surgery|disease|overdose|doctor/.test(low))this.add(G,`health_${G.age}_${low.slice(0,12)}`,'Health Memory',text,'health',4,{repeat:true});
      if(/million|wealth|net worth|property|house|vehicle|car/.test(low))this.add(G,`wealth_${G.age}_${low.slice(0,12)}`,'Wealth Memory',text,'wealth',3,{repeat:true});
      if(/donat|volunteer|helped|good karma/.test(low)){this.add(G,`kindness_${G.age}_${low.slice(0,12)}`,'Kindness Memory',text,'virtue',3,{repeat:true}); Moral.shift(G,{selfless:4,honest:2}); Reputation.shift(G,'public',2);}
      if(type==='bad'&&G.rels?.partner&&/partner|love|home|family|ego|argument/.test(low))this.relation(G,G.rels.partner,'hurt',text,{trust:-5,respect:-2,jealousy:3});
    },
    callbackEvent(G){const v=State.ensure(G); const memories=(v.memories||[]).filter(m=>m.weight>=3&&G.age-m.age>=6); if(!memories.length)return null; const m=pick(memories); const good=['family','virtue','career','education','love'].includes(m.category); return {icon:good?'🦋':'🕯️',type:good?'good':'bad',title:'Butterfly Effect',text:good?`A memory from age ${m.age} returns: ${m.text} Years later, that moment opens a new door.`:`A buried memory from age ${m.age} returns: ${m.text} The past asks to be paid back.`,choices:[{t:good?'Use the opportunity wisely':'Face it honestly',sub:'Memory callback',e:good?{happiness:5,reputation:3,money:rand(500,6000)}:{stress:5,happiness:-3,reputation:-2},memory:{id:`callback_${m.id}_${G.age}`,label:'Butterfly Effect',text:`The age ${m.age} memory changed your life again.`}},{t:'Move on quickly',sub:'Less emotional, less reward',e:good?{happiness:2}:{stress:2},memory:{id:`callback_ignore_${m.id}_${G.age}`,label:'Moved Past It',text:'You chose not to let the past define the year.'}}]};}
  };

  const Reputation={
    shift(G,key,delta){const v=State.ensure(G); if(!v)return; v.reputation[key]=clamp((v.reputation[key]??50)+delta, key==='criminal'?0:0,100); const avg=(v.reputation.family+v.reputation.career+v.reputation.public+v.reputation.romantic+v.reputation.business+v.reputation.online-v.reputation.criminal*.35)/5.65; G.reputation=clamp(Math.round(avg),0,100);},
    year(G){const v=State.ensure(G); if(!v)return; if((G.karma||0)>35)this.shift(G,'public',1); if((G.followers||0)>50000)this.shift(G,'online',1); if(G.career?.prestige>=7)this.shift(G,'career',1); if(G.business)this.shift(G,'business',1); if((G.crimes||[]).length>4)this.shift(G,'criminal',1); if((G.stress||0)>85)this.shift(G,'romantic',-1);}
  };

  const Moral={shift(G,d={}){const v=State.ensure(G); if(!v)return; Object.entries(d).forEach(([k,n])=>v.moral[k]=clamp((v.moral[k]??50)+n,0,100));}};

  const World={
    drift(G){const v=State.ensure(G); if(!v)return; const w=v.world; w.year=G.year||w.year||2026; ['economy','housing','crime','tech','healthcare','inflation','jobMarket','socialMood','politics','warRisk'].forEach(k=>{const volatility=k==='warRisk'?7:k==='tech'?8:6; w[k]=clamp((w[k]||50)+rand(-volatility,volatility),k==='warRisk'?0:5,100);}); if((G.age||0)>=18&&w.economy>72)G.money=(G.money||0)+rand(80,650); if(w.economy<28&&G.age>18){G.stress=clamp((G.stress||0)+rand(1,4)); if(Math.random()<.18)Engine?.log?.('📉 The weak economy made this year feel heavier.','bad');} if(w.healthcare<30&&G.age>45)G.health=clamp((G.health||50)-1); if((G.age||0)>=18&&w.tech>78&&G.skills){G.skillPoints=(G.skillPoints||0)+(Math.random()<.16?1:0);} if(w.crime>75&&G.age>=18&&Math.random()<.1)Secrets.add(G,'stolen_cash');},
    headline(G){const v=State.ensure(G); const w=v.world; const headline=this.playerHeadline(G); return {age:G.age,year:w.year,title:headline,economy:w.economy>65?'Booming':w.economy<35?'Weak':'Stable',culture:w.tech>70?'AI and digital fame dominate':w.socialMood>65?'Optimism returns':'People feel uncertain',crime:w.crime>67?'Scams and theft rising':w.crime<34?'Streets feel calmer':'Crime stays normal',politics:w.politics>65?'Tense public debate':w.warRisk>60?'Global fear rising':'Government stays quiet',ts:Date.now()};},
    playerHeadline(G){if(G.business)return `${G.name} expands ${G.business.name}`; if(G.career?.title)return `${G.name} pushes forward as ${G.career.title}`; if((G.rels?.children||[]).length)return `${G.name}'s family story grows`; if((G.fame||0)>50)return `${G.name} becomes harder to ignore`; if(net(G)>1000000)return `${G.name} enters the millionaire class`; return `${G.name}'s life turns another page`;},
    maybeNewspaper(G){const v=State.ensure(G); if(!v||G.age<8)return; if((G.age-(v.world.lastHeadlineAge||0)<1))return; const paper=this.headline(G); v.newspapers.unshift(paper); v.newspapers=v.newspapers.slice(0,30); v.world.lastHeadlineAge=G.age; if(G.age%4===0)Engine?.log?.(`🗞️ THE LIFE DAILY — ${paper.title}. Economy: ${paper.economy}. Culture: ${paper.culture}.`,'neutral');}
  };

  const Ambition={
    year(G){const v=State.ensure(G); if(!v)return; const arc=v.ambitionArc; if((G.age||0)<18){arc.score=0;arc.chapter=0;arc.chapterName=DATA.ambitionChapters[0];return;} const score=this.score(G); const old=arc.chapter||0; arc.score=score; arc.chapter=Math.min(4,Math.floor(score/22)); arc.chapterName=DATA.ambitionChapters[arc.chapter]; if(arc.chapter>old){const name=this.name(G); Memory.add(G,`ambition_chapter_${arc.chapter}_${G.age}`,`Ambition Chapter: ${arc.chapterName}`,`${name} entered chapter ${arc.chapter+1}: ${arc.chapterName}.`,'ambition',5); Engine?.log?.(`🎬 Ambition arc advanced: ${arc.chapterName}.`,'special'); arc.history.unshift({age:G.age,chapter:arc.chapter,name:arc.chapterName});}}
    ,score(G){const a=G.ambition; if(a==='wealth')return Math.min(100,net(G)/100000); if(a==='fame')return Math.min(100,(G.followers||0)/5000); if(a==='family')return Math.min(100,(G.rels?.partner?.married?35:0)+(G.rels?.children||[]).length*22+(G.v23.reputation.family||50)*.25); if(a==='career_top')return Math.min(100,(G.career?.level||G.career?.prestige||0)*10+(G.education==='university'?18:0)); if(a==='criminal')return Math.min(100,(G.crimes||[]).length*9+(G.v23.reputation.criminal||0)*.45); if(a==='entrepreneur')return Math.min(100,(G.business?.value||0)/1000000); if(a==='healthy'||a==='mindful')return Math.min(100,(G.age||0)*.6+(G.health||0)*.45+(100-(G.stress||0))*.25); return Math.min(100,(G.age||0)*.7+(G.reputation||50)*.35+(G.happiness||50)*.25);},
    name(G){try{return (typeof LIFE_AMBITIONS!=='undefined'&&LIFE_AMBITIONS.find(x=>x.id===G.ambition)?.name)||cap(G.ambition||'Life');}catch(_){return cap(G.ambition||'Life');}}
  };

  const RelationsPlus={
    year(G){const v=State.ensure(G); if(!v)return; Object.values(v.relationMemory).forEach(rm=>{ if(!rm)return; if((G.stress||0)>75){rm.trust=clamp((rm.trust||50)-1); if(Math.random()<.04)rm.currentProblem='feels the pressure around you';} if((G.karma||0)>50)rm.respect=clamp((rm.respect||50)+1); if(rm.currentProblem&&Math.random()<.08)rm.trust=clamp((rm.trust||50)-2); });},
    needEvent(G){const v=State.ensure(G); const probs=Object.values(v.relationMemory).filter(r=>r.currentProblem&&G.age>12); if(!probs.length)return null; const r=pick(probs); return {icon:'💬',type:'love',title:`${r.name} Needs You`,text:`${r.name} ${r.currentProblem}. This is not just a relationship bar — this is a memory being formed.`,choices:[{t:'Listen properly',sub:'+Trust, +Family reputation',e:{happiness:3,stress:-2,karma:2},fn:()=>{safeApply(G,{happiness:3,stress:-2,karma:2}); r.trust=clamp((r.trust||50)+8); r.respect=clamp((r.respect||50)+4); r.currentProblem=''; Memory.add(G,`listened_${r.name}_${G.age}`,`${r.name} felt heard`,`You listened when ${r.name} needed you.`,'relationship',4,{repeat:true}); Reputation.shift(G,'family',3); Moral.shift(G,{selfless:3,responsible:2});}},{t:'Brush it off',sub:'Fast, but trust drops',e:{stress:-1,happiness:-2},fn:()=>{safeApply(G,{stress:-1,happiness:-2}); r.trust=clamp((r.trust||50)-9); r.history.unshift({age:G.age,kind:'ignored',text:'You brushed off their concern.'}); Memory.add(G,`ignored_${r.name}_${G.age}`,`${r.name} remembered being ignored`,`You avoided a serious conversation with ${r.name}.`,'relationship',3,{repeat:true}); Moral.shift(G,{selfless:-3,responsible:-2});}}]};}
  };

  const Rivals={
    ensure(G){const v=State.ensure(G); if(!v)return; if(v.rivals.length||G.age<10)return; this.create(G,'school rival');},
    create(G,role){const gender=Math.random()>.5?'female':'male'; const npc=Engine?.npc?Engine.npc('rival',gender):{name:gender==='female'?'Mia':'Adam',surname:G.surname,gender}; const r={id:`r_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,name:npc.name||'Rival',surname:npc.surname||'',role:role||pick(DATA.rivalRoles),age:G.age+rand(-2,2),respect:rand(18,62),threat:rand(22,78),success:rand(10,45),history:[]}; State.ensure(G).rivals.push(r); Memory.add(G,`rival_${r.id}`,`Rival Appeared`,`${r.name} became your ${r.role}.`,'rival',4); return r;},
    year(G){const v=State.ensure(G); if(!v)return; if(!v.rivals.length&&G.age>=10&&Math.random()<.15)this.create(G,pick(DATA.rivalRoles)); v.rivals.forEach(r=>{r.age=(r.age||G.age)+1; r.success=clamp((r.success||20)+rand(-3,8)+(r.threat>60?2:0)); if(Math.random()<.04)r.respect=clamp((r.respect||35)+rand(-6,8));});},
    event(G){const v=State.ensure(G); const r=pick(v?.rivals||[]); if(!r||G.age<14)return null; const helping=(r.respect||0)>55; return {icon:helping?'🤝':'⚔️',type:helping?'good':'bad',title:`${r.name} Returns`,text:helping?`${r.name}, once your ${r.role}, has grown successful and surprisingly respectful. They offer a chance to work together.`:`${r.name}, your ${r.role}, makes a move that threatens your reputation. Rivalries age too.`,choices:helping?[{t:'Build an alliance',sub:'Rival can become useful',e:{reputation:4,money:rand(1000,9000),stress:2},fn:()=>{safeApply(G,{reputation:4,money:rand(1000,9000),stress:2});r.respect=clamp((r.respect||50)+10);Memory.add(G,`rival_alliance_${r.id}_${G.age}`,'Rival Alliance',`${r.name} became an unexpected ally.`,'rival',5,{repeat:true});Reputation.shift(G,'public',3);}},{t:'Keep distance',e:{stress:-3},fn:()=>{safeApply(G,{stress:-3});r.respect=clamp((r.respect||50)-3);}}]:[{t:'Confront them publicly',sub:'Risky but powerful',e:{fame:4,stress:5,reputation:3},fn:()=>{safeApply(G,{fame:4,stress:5,reputation:3});r.threat=clamp((r.threat||50)-8);r.respect=clamp((r.respect||30)+6);Memory.add(G,`rival_confront_${r.id}_${G.age}`,'Rival Confronted',`You confronted ${r.name}.`,'rival',4,{repeat:true});Moral.shift(G,{risk:4});}},{t:'Stay calm and strategic',e:{smarts:3,stress:-1},fn:()=>{safeApply(G,{smarts:3,stress:-1});r.threat=clamp((r.threat||50)-4);Moral.shift(G,{responsible:4});}}]};}
  };

  const Secrets={
    add(G,id){const v=State.ensure(G); if(!v)return null; const def=DATA.secrets.find(s=>s.id===id)||pick(DATA.secrets); if(!def||v.secrets.some(s=>s.id===def.id&&!s.discovered))return null; const sec={...def,age:G.age||0,discovered:false,heat:rand(12,46)}; v.secrets.unshift(sec); Memory.add(G,`secret_${def.id}_${G.age}`,`Secret Created: ${def.name}`,`A secret entered your life. It may return later.`,'secret',4,{hidden:true,repeat:true}); return sec;},
    year(G){const v=State.ensure(G); if(!v)return; if(G.age>=18&&v.secrets.length<3&&Math.random()<.035){const pool=DATA.secrets.filter(s=>s.risk!=='good'||(G.karma||0)>20); const s=pick(pool); if(s)this.add(G,s.id);} v.secrets.forEach(s=>{if(!s.discovered)s.heat=clamp((s.heat||20)+rand(-3,7));});},
    event(G){const v=State.ensure(G); const s=(v?.secrets||[]).filter(x=>!x.discovered&&x.heat>55)[0]; if(!s)return null; return {icon:s.icon||'🔒',type:s.risk==='good'?'good':'bad',title:'A Secret Surfaces',text:`The secret "${s.name}" is close to being exposed. What you do now will shape reputation and trust.`,choices:[{t:'Confess before it leaks',sub:'Painful but cleaner',e:{stress:4,reputation:-2,karma:4},fn:()=>{safeApply(G,{stress:4,reputation:-2,karma:4});s.discovered=true;s.resolved='confessed';Memory.add(G,`secret_confessed_${s.id}_${G.age}`,'Secret Confessed',`You confessed: ${s.name}.`,'secret',5,{repeat:true});Moral.shift(G,{honest:7,responsible:3});Reputation.shift(G,'public',-1);}},{t:'Hide it harder',sub:'Short-term relief, bigger future risk',e:{stress:7,karma:-3},fn:()=>{safeApply(G,{stress:7,karma:-3});s.heat=clamp((s.heat||50)+18);Memory.add(G,`secret_hidden_${s.id}_${G.age}`,'Secret Buried Deeper',`You tried to hide ${s.name}.`,'secret',4,{repeat:true});Moral.shift(G,{honest:-6,responsible:-3});}}]};}
  };

  const Fate={year(G){const v=State.ensure(G); if(!v)return; const ids=new Set(v.fateCards.map(f=>f.id)); DATA.fate.forEach(f=>{if(!ids.has(f.id)||v.fateRevealed[f.id])return; let ok=false; try{ok=f.trigger(G);}catch(_){ok=false;} if(ok){v.fateRevealed[f.id]=true; const card=v.fateCards.find(x=>x.id===f.id); if(card)card.revealed=true; safeApply(G,f.e||{}); Memory.add(G,`fate_${f.id}`,`Fate Revealed: ${f.name}`,f.text,'fate',6); Engine?.log?.(`${f.icon} Fate card revealed: ${f.name}. ${f.text}`,'special'); window.LifeSimV22?.FX?.confetti?.(18);}});}};

  const Temptations={
    event(G){const t=G.trait; if(!t||G.age<18)return null; const map={lazy:{icon:'🛋️',title:'The Easy Way Out',text:'Your lazy side wants comfort instead of progress. The year offers a shortcut: rest now, pay later.',give:{t:'Give in to comfort',e:{happiness:5,stress:-6,smarts:-2,fitness:-2},m:{responsible:-5}},resist:{t:'Force discipline',e:{smarts:4,fitness:2,stress:4},m:{responsible:6}}},arrogant:{icon:'👑',title:'Ego Check',text:'Someone questions you. Your arrogant side wants to dominate the moment instead of learning from it.',give:{t:'Put them in their place',e:{fame:4,karma:-4,stress:2},m:{selfless:-4,honest:-2}},resist:{t:'Stay humble',e:{reputation:4,smarts:2,stress:-1},m:{selfless:5,honest:3}}},honest:{icon:'🤝',title:'The Clean Choice',text:'A useful lie would make life easier. Your honest side refuses to let it feel simple.',give:{t:'Tell the useful lie',e:{money:rand(700,3500),karma:-6,stress:5},m:{honest:-8}},resist:{t:'Tell the truth',e:{karma:8,reputation:4,money:-500},m:{honest:8,responsible:3}}},introvert:{icon:'🌙',title:'Invitation Pressure',text:'You are invited into a social situation that could help your future but drain your energy.',give:{t:'Stay home and recharge',e:{stress:-7,smarts:2,happiness:2},m:{risk:-2}},resist:{t:'Go anyway',e:{fame:2,reputation:3,stress:4},m:{risk:4}}},extrovert:{icon:'🎉',title:'Attention Trap',text:'A fun night could become a great story or an expensive mistake.',give:{t:'Make it legendary',e:{happiness:7,fame:3,money:-900,stress:3},m:{risk:6}},resist:{t:'Leave early',e:{stress:-3,money:300},m:{responsible:4}}},curious:{icon:'🧭',title:'Dangerous Question',text:'You discover something strange. Curiosity wants answers even if it complicates life.',give:{t:'Investigate',e:{smarts:6,stress:3},m:{risk:4}},resist:{t:'Let it go',e:{stress:-3,happiness:1},m:{responsible:2}}}}; const d=map[t]; if(!d)return null; return {icon:d.icon,type:'special',title:d.title,text:d.text,choices:[{t:d.give.t,sub:'Trait temptation',e:d.give.e,fn:()=>{safeApply(G,d.give.e);Moral.shift(G,d.give.m);Memory.add(G,`tempt_${t}_give_${G.age}`,`${cap(t)} Temptation`,d.give.t,'personality',4,{repeat:true});}},{t:d.resist.t,sub:'Shape your identity',e:d.resist.e,fn:()=>{safeApply(G,d.resist.e);Moral.shift(G,d.resist.m);Memory.add(G,`tempt_${t}_resist_${G.age}`,`${cap(t)} Growth`,d.resist.t,'personality',5,{repeat:true});}}]};}
  };

  const Procedural={
    event(G){const v=State.ensure(G); if(!v)return null; const w=v.world,d=v.dna; const scene=pick(['a rainy evening','a crowded train ride','a quiet morning','a tense phone call','a late-night message','a small cafe conversation','a family dinner','a workplace rumor']); const pressure=w.economy<35?'money pressure':w.crime>70?'rising local crime':w.tech>75?'a sudden tech opportunity':w.politics>70?'a tense public mood':(G.stress||0)>70?'private burnout':'a strange opportunity'; const conflict=pick(['moral choice','family pressure','dangerous offer','career shortcut','relationship test','public risk']); const title=pick(['Crossroads With Consequences','A Year That Might Echo','The Choice Beneath the Choice','A Door Opens Sideways']); return {icon:'🧩',type:'special',title,text:`During ${scene}, ${pressure} turns into a ${conflict}. Your age, country, personality, world conditions and memories all point toward different futures.`,choices:[{t:'Choose the safe path',sub:'Responsible, lower upside',e:{stress:-3,happiness:2,money:rand(0,900)},fn:()=>{safeApply(G,{stress:-3,happiness:2,money:rand(0,900)});Moral.shift(G,{risk:-4,responsible:5});Memory.add(G,`proc_safe_${G.age}_${Date.now()}`,'Chose Safety','You chose the stable path during a complex year.','choice',3,{repeat:true});}},{t:'Take the risky opportunity',sub:'High upside, future callback',e:{money:rand(500,9000),fame:3,stress:6},fn:()=>{safeApply(G,{money:rand(500,9000),fame:3,stress:6});Moral.shift(G,{risk:7,responsible:-2});Memory.add(G,`proc_risk_${G.age}_${Date.now()}`,'Risk Taken','You took a chance that could echo later.','choice',5,{repeat:true}); if(Math.random()<.18)Secrets.add(G,pick(['hidden_debt','fake_story','stolen_cash']));}},{t:'Protect someone else',sub:'Relationship memory',e:{karma:5,happiness:3,stress:2},fn:()=>{safeApply(G,{karma:5,happiness:3,stress:2});Moral.shift(G,{selfless:7,honest:2});Reputation.shift(G,'family',3);Memory.add(G,`proc_protect_${G.age}_${Date.now()}`,'Protected Someone','You put another person first.','virtue',5,{repeat:true});}},{t:'Use it for your ambition',sub:'Arc progress',e:{smarts:3,fame:2,stress:4},fn:()=>{safeApply(G,{smarts:3,fame:2,stress:4});Moral.shift(G,{responsible:2,risk:3});Memory.add(G,`proc_ambition_${G.age}_${Date.now()}`,'Ambition First','You made the choice serve your long-term ambition.','ambition',4,{repeat:true});}}]};},
    youthEvent(G){const scene=pick(['a difficult school week','a changing friendship','a family conversation','an online disagreement','a new responsibility','a question about the future']); const title=pick(['A Choice While Growing Up','A Week That Teaches You Something','Friends, Family and the Future','A Small Decision With Weight']); return {icon:'🧭',type:'special',title,text:`During ${scene}, you have to choose how to respond. This is about learning who you are—not earning adult money or carrying adult pressure.`,choices:[{t:'Ask a trusted adult',sub:'Get support and perspective',e:{stress:-5,happiness:3,parentBond:3}},{t:'Make a realistic school plan',sub:'Steady progress without burnout',e:{smarts:3,schoolPerformance:6,stress:1}},{t:'Protect an important friendship',sub:'Choose connection and respect',e:{happiness:5,karma:3,reputation:1}},{t:'Take a healthy reset',sub:'Rest, move and come back clearer',e:{health:3,mentalHealth:5,stress:-6}}]};},
    should(G,key,gap,chance){const v=State.ensure(G); const last=v[key]??-99; if((G.age-last)<gap)return false; if(Math.random()>chance)return false; v[key]=G.age; return true;},
    inject(queue){const G=window.G;if(!G||!Array.isArray(queue)||G.inPrison)return; State.ensure(G); const limit=G.age<18?2:3; const room=()=>queue.length<limit; if(room()&&G.age>=13&&G.age<18&&this.should(G,'lastV23YouthProcedural',3,.36))queue.push(this.youthEvent(G)); else if(room()&&G.age>=18&&this.should(G,'lastV23Procedural',3,.42))queue.push(this.event(G)); if(room()&&G.age>=18&&this.should(G,'lastTemptation',4,.34)){const e=Temptations.event(G); if(e)queue.push(e);} if(room()&&G.age>=18&&this.should(G,'lastMemoryCallback',5,.30)){const e=Memory.callbackEvent(G); if(e)queue.push(e);} if(room()&&G.age>=12&&this.should(G,'lastRelationNeed',4,.26)){const e=RelationsPlus.needEvent(G); if(e)queue.push(e);} if(room()&&G.age>=18&&this.should(G,'lastRivalEvent',5,.23)){const e=Rivals.event(G); if(e)queue.push(e);} if(room()&&G.age>=18&&this.should(G,'lastSecretEvent',4,.22)){const e=Secrets.event(G); if(e)queue.push(e);} }
  };

  const UI23={
    installDom(){document.body.classList.add('v23-active'); $('#app')?.setAttribute('data-build','v23.2'); let line=$('.v23-topline'); if(!line){line=document.createElement('div');line.className='v23-topline';document.body.appendChild(line);} if(!$('#tab-codex')){const panel=document.createElement('div');panel.id='tab-codex';panel.className='tab-panel';document.getElementById('game-content')?.appendChild(panel);} if(!$('.nt[data-tab="codex"]')){const btn=document.createElement('button');btn.type='button';btn.className='nt v23-codex-tab';btn.dataset.tab='codex';btn.onclick=()=>UI.tab('codex');btn.innerHTML='<span class="ni" aria-hidden="true">📜</span><span class="nl">Codex</span><span class="tab-dot" id="dot-codex"></span>'; const nav=$('.nav-bar'); nav?.appendChild(btn);} document.title='LifeSim v23.2'; const meta=document.querySelector('meta[name="description"]'); if(meta)meta.content='LifeSim v23.2 — age-aware progression, memory, consequences, world simulation, rivals, secrets and dynasty.';},
    mini(label,value,detail,pct,cls=''){return `<div class="v23-mini ${cls}"><span>${esc(label)}</span><b>${esc(value)}</b><em>${esc(detail||'')}</em>${pct!==null&&pct!==undefined?`<div class="v23-bar"><i style="width:${clamp(pct)}%"></i></div>`:''}</div>`;},
    avatar(G){const age=G.age||0; let face=G.gender==='female'?'👩':'👨'; if(age<13)face=G.gender==='female'?'👧':'👦'; else if(age>64)face=G.gender==='female'?'👵':'👴'; if((G.fame||0)>80)face='🌟'; if((G.v23?.reputation?.criminal||0)>70)face='🕶️'; if((G.health||0)<25)face='😷'; if((G.happiness||0)>85)face='😁'; return face;},
    dashboard(){const G=window.G;if(!G||!$('#tab-life'))return; const tab=$('#tab-life'); const sig=`${G.ageUpSerial||0}-${(G.log||[]).length}-${(G.v23?.memories||[]).length}`; if(tab.dataset.v23Dash===sig)return; $$('.v23-command-center,.v23-newspaper-card',tab).forEach(n=>n.remove()); const v=State.ensure(G); const anchor=$('.v22-life-map',tab)||$('.life-view-shell',tab)||tab.firstElementChild; if(!anchor)return; const paper=v.newspapers?.[0]; if(paper){const el=document.createElement('div');el.className='v23-newspaper-card';el.innerHTML=this.newspaperHTML(paper); anchor.insertAdjacentElement('beforebegin',el);} const cc=document.createElement('section');cc.className='v23-command-center';cc.innerHTML=this.commandHTML(G); anchor.insertAdjacentElement('beforebegin',cc); tab.dataset.v23Dash=sig;},
    commandHTML(G){const v=State.ensure(G); const memories=(v.memories||[]).slice(0,3); const rival=v.rivals?.[0]; const arc=v.ambitionArc; const quote=this.lifeMotto(G); return `<div class="v23-hero-row"><div class="v23-avatar-card"><div class="v23-avatar">${this.avatar(G)}</div><div class="v23-avatar-meta"><div class="v23-kicker">Character Profile</div><h2>${esc(G.name)} ${esc(G.surname||'')}</h2><p>Age ${esc(G.age||0)} · ${esc(G.country?.name||'Unknown')} · ${esc(cap(G.trait||'Unwritten'))}</p><div class="v23-quote">“${esc(quote)}”</div></div></div><div class="v23-panel"><div class="v23-kicker">Life Command Center</div><h3 class="v23-title">${esc(arc.chapterName)} — ${esc(Ambition.name(G))}</h3><p class="v23-copy">Mood: <b>${esc(v.mentalState)}</b>. Main risk: <b>${esc(this.mainRisk(G))}</b>. Recent memory: <b>${esc(memories[0]?.label||'none yet')}</b>.</p><div class="v23-grid" style="margin-top:12px">${this.mini('Ambition',`${Math.round(arc.score||0)}%`,arc.chapterName,arc.score)}${this.mini('Legacy',State.legacyScore(G),'dynasty score',Math.min(100,State.legacyScore(G)/5))}${this.mini('World',this.worldLabel(v.world),`economy ${Math.round(v.world.economy)}`,v.world.economy)}${this.mini('Rival',rival?rival.name:'none yet',rival?`${rival.role} · threat ${Math.round(rival.threat)}`:'story will generate',rival?rival.threat:0)}</div></div></div><div class="v23-card-grid"><div class="v23-panel"><div class="v23-kicker">Permanent Memories</div><h3 class="v23-title">Choices now echo later</h3><div class="v23-memory-list">${memories.length?memories.map(m=>this.memoryItem(m)).join(''):'<div class="v23-memory"><div class="v23-memory-top"><b>No memories yet</b><span class="v23-age">Age 0</span></div><p>Major choices will be stored here and can return years later.</p></div>'}</div></div><div class="v23-panel"><div class="v23-kicker">Reputation DNA</div><h3 class="v23-title">Not one karma bar anymore</h3>${this.repBars(G)}<div class="v23-chip-row"><span class="v23-chip">🧬 hidden DNA active</span><span class="v23-chip">🃏 ${v.fateCards.filter(f=>f.revealed).length}/${v.fateCards.length} fates revealed</span></div></div></div>`;},
    memoryItem(m){return `<article class="v23-memory"><div class="v23-memory-top"><b>${esc(m.label)}</b><span class="v23-age">Age ${esc(m.age)}</span></div><p>${esc(m.text)}</p></article>`;},
    repBars(G){const v=State.ensure(G); return `<div class="v23-moral-grid">${DATA.reputationKeys.map(([k,l])=>`<div class="v23-axis"><span>${esc(l)}</span><div class="v23-axis-track"><div class="v23-axis-fill" style="width:${clamp(v.reputation[k]??50)}%"></div></div><span>${Math.round(v.reputation[k]??50)}</span></div>`).join('')}</div>`;},
    moralBars(G){const v=State.ensure(G); return `<div class="v23-moral-grid">${DATA.moralAxes.map(([k,l,r])=>`<div class="v23-axis"><span>${esc(l)}</span><div class="v23-axis-track"><div class="v23-axis-fill" style="width:${clamp(v.moral[k]??50)}%"></div></div><span>${esc(r)}</span></div>`).join('')}</div>`;},
    newspaperHTML(p){return `<div class="v23-newspaper-head"><div><div class="v23-paper-name">THE LIFE DAILY</div><div class="v23-paper-date">Year ${esc(p.year)} · Age ${esc(p.age)}</div></div><span class="v23-chip">world sim</span></div><div class="v23-headline">${esc(p.title)}</div><div class="v23-paper-cols"><div><b>Economy</b><span>${esc(p.economy)}</span></div><div><b>Culture</b><span>${esc(p.culture)}</span></div><div><b>Crime</b><span>${esc(p.crime)}</span></div><div><b>Politics</b><span>${esc(p.politics)}</span></div></div>`;},
    worldLabel(w){if(!w)return'Unknown'; if(w.economy>70)return'Boom'; if(w.economy<32)return'Recession'; if(w.crime>74)return'Danger'; if(w.tech>78)return'Tech wave'; return'Stable';},
    mainRisk(G){const v=State.ensure(G); if((G.health||0)<35)return'health collapse'; if((G.stress||0)>75)return'burnout'; if(v.world.economy<30)return'recession pressure'; if(v.secrets.some(s=>!s.discovered&&s.heat>55))return'secret exposure'; if(v.rivals.some(r=>r.threat>70))return'rival attack'; if(!G.career&&G.age>22)return'lost direction'; return'complacency';},
    lifeMotto(G){const v=State.ensure(G); if((v.moral.selfless||50)>70)return'What I give becomes what remains.'; if((v.moral.risk||50)>70)return'Safe lives rarely become legends.'; if((v.moral.honest||50)>70)return'The truth costs less than a hidden life.'; if((G.fame||0)>70)return'Being seen is not the same as being known.'; if(net(G)>1000000)return'Money is a tool. Legacy is the test.'; return'Every year writes a sentence I cannot erase.';},
    renderCodex(){const G=window.G,el=$('#tab-codex'); if(!G||!el)return; const v=State.ensure(G); const section=v.codexFilter||'memories'; el.innerHTML=`<div class="v23-codex-shell"><div class="v23-codex-head"><div><div class="v23-kicker">Life Codex</div><h2 class="v23-title" style="font-size:26px">Memory, secrets, rivals, dynasty and world state</h2><p class="v23-copy">This is the deep layer: the game remembers who you became, not only what your current stats are.</p></div><div class="v23-codex-nav">${['memories','relations','world','rivals','secrets','dynasty','dna'].map(k=>`<button type="button" class="${section===k?'active':''}" onclick="LifeSimV23.UI.setCodex('${k}')">${esc(cap(k))}</button>`).join('')}</div></div><div class="v23-codex-section ${section==='memories'?'active':''}">${this.memoriesHTML(v)}</div><div class="v23-codex-section ${section==='relations'?'active':''}">${this.relationsHTML(v)}</div><div class="v23-codex-section ${section==='world'?'active':''}">${this.worldHTML(v)}</div><div class="v23-codex-section ${section==='rivals'?'active':''}">${this.rivalsHTML(v)}</div><div class="v23-codex-section ${section==='secrets'?'active':''}">${this.secretsHTML(v)}</div><div class="v23-codex-section ${section==='dynasty'?'active':''}">${this.dynastyHTML(v)}</div><div class="v23-codex-section ${section==='dna'?'active':''}">${this.dnaHTML(v)}</div></div>`;},
    setCodex(k){const G=window.G;if(!G)return; State.ensure(G).codexFilter=k; this.renderCodex();},
    memoriesHTML(v){const items=(v.memories||[]).slice(0,40); return `<div class="v23-codex-grid">${items.length?items.map(m=>`<div class="v23-panel"><div class="v23-kicker">${esc(m.category)} · age ${esc(m.age)}</div><h3 class="v23-title">${esc(m.label)}</h3><p class="v23-copy">${esc(m.hidden?'Hidden memory — consequences may surface later.':m.text)}</p></div>`).join(''):'<div class="v23-panel v23-full"><h3 class="v23-title">No permanent memories yet.</h3><p class="v23-copy">Events and choices will populate this section.</p></div>'}</div>`;},
    relationsHTML(v){const arr=Object.values(v.relationMemory||{}); return `<div class="v23-codex-grid">${arr.length?arr.map(r=>`<div class="v23-panel"><div class="v23-kicker">${esc(r.role)} · ${esc(r.personality)}</div><h3 class="v23-title">${esc(r.name)}</h3><p class="v23-copy">Trust ${Math.round(r.trust||0)} · Respect ${Math.round(r.respect||0)} · Jealousy ${Math.round(r.jealousy||0)}${r.currentProblem?' · Problem: '+esc(r.currentProblem):''}</p><div class="v23-memory-list">${(r.history||[]).slice(0,3).map(h=>`<div class="v23-memory"><div class="v23-memory-top"><b>${esc(h.kind)}</b><span class="v23-age">Age ${esc(h.age)}</span></div><p>${esc(h.text)}</p></div>`).join('')}</div></div>`).join(''):'<div class="v23-panel v23-full"><h3 class="v23-title">Relationships have no memory yet.</h3><p class="v23-copy">Partner, family, friends and children will start remembering meaningful moments.</p></div>'}</div>`;},
    worldHTML(v){const w=v.world; return `<div class="v23-codex-grid"><div class="v23-panel">${this.newspaperHTML(v.newspapers?.[0]||World.headline(window.G))}</div><div class="v23-panel"><div class="v23-kicker">World Simulation</div><h3 class="v23-title">The world pushes back</h3>${['economy','housing','crime','tech','healthcare','inflation','jobMarket','socialMood','politics','warRisk'].map(k=>`<div class="v23-axis"><span>${esc(cap(k))}</span><div class="v23-axis-track"><div class="v23-axis-fill" style="width:${clamp(w[k])}%"></div></div><span>${Math.round(w[k])}</span></div>`).join('')}</div></div>`;},
    rivalsHTML(v){return `<div class="v23-codex-grid">${(v.rivals||[]).length?v.rivals.map(r=>`<div class="v23-panel"><div class="v23-kicker">${esc(r.role)}</div><h3 class="v23-title">${esc(r.name)} ${esc(r.surname||'')}</h3><p class="v23-copy">Age ${Math.round(r.age||0)} · Threat ${Math.round(r.threat||0)} · Respect ${Math.round(r.respect||0)} · Success ${Math.round(r.success||0)}</p></div>`).join(''):'<div class="v23-panel v23-full"><h3 class="v23-title">No rivals yet.</h3><p class="v23-copy">Rivals can appear through school, work, business, romance, sport, or crime.</p></div>'}</div>`;},
    secretsHTML(v){return `<div class="v23-codex-grid">${(v.secrets||[]).length?v.secrets.map(s=>`<div class="v23-panel"><div class="v23-kicker">${esc(s.risk)} · age ${esc(s.age)}</div><h3 class="v23-title">${s.discovered?esc(s.name):'Undiscovered Secret'}</h3><p class="v23-copy">${s.discovered?'Resolved: '+esc(s.resolved||'exposed'):`Heat ${Math.round(s.heat||0)} · It may surface later.`}</p></div>`).join(''):'<div class="v23-panel v23-full"><h3 class="v23-title">No secrets yet.</h3><p class="v23-copy">Some risky decisions can create secrets that return years later.</p></div>'}</div>`;},
    dynastyHTML(v){const t=v.familyTree; return `<div class="v23-codex-grid"><div class="v23-panel"><div class="v23-kicker">Dynasty</div><h3 class="v23-title">${esc(t.surname||'Family')} Legacy</h3><p class="v23-copy">Founder: ${esc(t.founder||'Unknown')} · Members: ${(t.members||[]).length} · Heirs: ${(t.heirs||[]).length} · Legacy score: ${Math.round(t.legacyScore||0)}</p></div>${(t.heirs||[]).map(h=>`<div class="v23-panel"><div class="v23-kicker">Possible heir</div><h3 class="v23-title">${esc(h.name)}</h3><p class="v23-copy">Age ${esc(h.age)} · ${esc(h.trait)} · dreams of ${esc(h.dream)}</p></div>`).join('')}</div>`;},
    dnaHTML(v){return `<div class="v23-codex-grid"><div class="v23-panel"><div class="v23-kicker">Life DNA</div><h3 class="v23-title">Hidden personality engine</h3><p class="v23-copy">This affects temptation, risk, luck, discipline, empathy and the kinds of stories that appear.</p>${Object.entries(v.dna||{}).map(([k,val])=>`<div class="v23-axis"><span>${esc(cap(k))}</span><div class="v23-axis-track"><div class="v23-axis-fill" style="width:${clamp(val)}%"></div></div><span>${Math.round(val)}</span></div>`).join('')}</div><div class="v23-panel"><div class="v23-kicker">Fate Cards</div><h3 class="v23-title">Hidden triggers</h3><div class="v23-fate-list">${(v.fateCards||[]).map(f=>`<div class="v23-fate"><p>${f.revealed?`${esc(f.icon)} ${esc(f.name)} — revealed`:'🂠 Unknown fate — not revealed yet'}</p></div>`).join('')}</div>${this.moralBars(window.G)}</div></div>`;},
    deathLegend(){const G=window.G;if(!G||!$('#death-screen.active')&&!$('#death-screen'))return; const body=$('.death-story')||$('#dt-story'); if(!body||$('.v23-death-legend'))return; const v=State.ensure(G); const biggest=(v.memories||[]).sort((a,b)=>(b.weight||0)-(a.weight||0))[0]; const regret=(v.memories||[]).find(m=>['crime','secret'].includes(m.category))||Object.values(v.relationMemory||{}).find(r=>(r.trust||50)<30); const heirs=(v.familyTree?.heirs||[]).length; const el=document.createElement('section');el.className='v23-death-legend';el.innerHTML=`<div class="v23-kicker">Legendary Life Recap</div><h3 class="v23-title">${esc(G.name)} did not just die — a biography closed.</h3><div class="v23-death-grid">${this.mini('Legacy score',State.legacyScore(G),'family + memory',null)}${this.mini('Memories',(v.memories||[]).length,'permanent tags',null)}${this.mini('Heirs',heirs,'dynasty continuation',null)}${this.mini('Fates',`${(v.fateCards||[]).filter(f=>f.revealed).length}/${(v.fateCards||[]).length}`,'revealed',null)}</div><div class="v23-grave">Grave inscription: “${esc(this.lifeMotto(G))}”</div><p class="v23-copy"><b>Defining memory:</b> ${esc(biggest?.text||'A quiet life with unwritten echoes.')}</p><p class="v23-copy"><b>Biggest unresolved shadow:</b> ${esc(regret?.text||regret?.currentProblem||'No obvious regret recorded.')}</p>${heirs?'<button type="button" class="btn-primary" onclick="LifeSimV23.Dynasty.continueAsHeir()">🌳 Continue as Heir</button>':''}`; body.insertAdjacentElement('afterend',el);},
  };

  const Dynasty={continueAsHeir(){const old=window.G; const v=State.ensure(old); const heir=(v.familyTree?.heirs||[])[0]; if(!heir){UI?.toast?.('No heir available.','neutral');return;} try{App?.newLife?.(); setTimeout(()=>{const nameInput=$('#inp-name'); if(nameInput)nameInput.value=heir.name.split(' ')[0]||heir.name; const diff=$('#inp-diff'); if(diff)diff.value='normal'; UI?.toast?.(`Heir selected: ${heir.name}. Start their life to continue the dynasty.`,'good');},250);}catch(e){console.warn(e); UI?.toast?.('Heir mode could not start automatically.','bad');}}};

  function enhanceChoices(evt){if(!evt||evt._v23Choices)return evt; const choices=(evt.choices&&evt.choices.length?evt.choices:[{t:'Continue',e:{}}]).map(c=>{const orig={...c}; const originalFn=c.fn; const effect=c.e||{}; return {...c,fn:function(){const G=window.G; State.ensure(G); const before=G?{money:G.money,happiness:G.happiness,health:G.health,stress:G.stress,reputation:G.reputation}:null; if(typeof originalFn==='function')originalFn(); else safeApply(G,effect); if(orig.memory)Memory.add(G,orig.memory.id,orig.memory.label,orig.memory.text,orig.memory.category||'choice',orig.memory.weight||4,{repeat:true}); if(orig.moral)Moral.shift(G,orig.moral); if(orig.rep)Object.entries(orig.rep).forEach(([k,n])=>Reputation.shift(G,k,n)); if(G&&evt.title){const label=orig.t||orig.label||'choice'; Memory.add(G,`decision_${String(evt.title).toLowerCase().replace(/[^a-z0-9]+/g,'_')}_${G.age}_${Date.now()}`,evt.title,`Chose: ${label}`,'decision',orig.memoryWeight||3,{repeat:true}); if(before){const moneyDelta=(G.money||0)-(before.money||0); if(moneyDelta>2500)Reputation.shift(G,'career',1); if((G.stress||0)>before.stress+5)Moral.shift(G,{responsible:-1});}} }};}); return {...evt,choices,_v23Choices:true};}

  function yearTick(){const G=window.G;if(!G||!G.alive)return; State.ensure(G); World.drift(G); Reputation.year(G); RelationsPlus.year(G); Rivals.ensure(G); Rivals.year(G); Secrets.year(G); Fate.year(G); Ambition.year(G); World.maybeNewspaper(G); State.ensureFamilyTree(G); State.mentalState(G);}

  function patch(){
    if(window.__LifeSimV23Patched)return; window.__LifeSimV23Patched=true; UI23.installDom();
    try{ if(Array.isArray(window.LIFESIM_UPDATES)&&!window.LIFESIM_UPDATES.some(u=>u.version==='v23'))window.LIFESIM_UPDATES.unshift({version:'v23',title:'Memory & Consequences',date:'2026-07-09',tag:'Major Upgrade',highlights:['Permanent memory tags make choices return years later.','Relationship memory adds trust, respect, jealousy, history and current problems.','Family tree and dynasty groundwork with possible heirs.','Ambition arcs now have chapters like a playable biography.','World simulation generates yearly newspapers and external pressure.','Rivals, secrets, fate cards, moral alignment and hidden Life DNA deepen replayability.','Codex tab tracks memories, world state, relations, rivals, secrets, dynasty and DNA.','Legendary death recap adds grave inscription, regrets, defining memories and heir continuation.']}); }catch(_){ }
    if(window.Engine&&!Engine._v23Patched){
      if(Array.isArray(Engine._moduleOrder)&&!Engine._moduleOrder.includes('LifeSimV23.yearTick'))Engine._moduleOrder.splice(1,0,'LifeSimV23.yearTick');
      const oldLog=Engine.log?.bind(Engine); if(oldLog)Engine.log=function(text,type='neutral'){const out=oldLog(text,type); try{Memory.inferFromLog(window.G,text,type);}catch(e){console.warn('v23 log memory',e);} return out;};
      const oldQueue=Engine._queueEvents?.bind(Engine); if(oldQueue)Engine._queueEvents=function(queue){oldQueue(queue); try{Procedural.inject(queue);}catch(e){console.warn('v23 queue',e);} };
      const oldDie=Engine._die?.bind(Engine); if(oldDie)Engine._die=function(cause){try{Memory.add(window.G,`death_${window.G?.age}`,'Final Chapter',`Life ended from ${cause}.`,'death',8,{repeat:true}); State.ensureFamilyTree(window.G);}catch(_){ } const out=oldDie(cause); setTimeout(()=>UI23.deathLegend(),120); return out;};
      Engine._v23Patched=true;
    }
    if(window.UI&&!UI._v23Patched){
      const oldRender=UI._renderTab?.bind(UI); if(oldRender)UI._renderTab=function(name){if(name==='codex'){UI23.renderCodex();return;} return oldRender(name);};
      const oldUpdate=UI.update?.bind(UI); if(oldUpdate)UI.update=function(){const out=oldUpdate(); requestAnimationFrame(()=>{UI23.installDom(); UI23.dashboard(); if(UI._activeTab==='codex')UI23.renderCodex();}); return out;};
      const oldRefresh=UI.refreshActiveTab?.bind(UI); if(oldRefresh)UI.refreshActiveTab=function(){const out=oldRefresh(); requestAnimationFrame(()=>{if(UI._activeTab==='codex')UI23.renderCodex();UI23.dashboard();}); return out;};
      const oldShow=UI.showEvent?.bind(UI); if(oldShow)UI.showEvent=function(evt,cb){const modal=$('#ev-modal'); if(modal)modal.classList.add('v23-cinematic'); const out=oldShow(enhanceChoices(evt),function(){if(modal)modal.classList.remove('v23-cinematic'); if(cb)cb();}); setTimeout(()=>{const t=$('#m-title'); if(t&&!$('.v23-choice-hint')){const hint=document.createElement('div');hint.className='v23-choice-hint';hint.style.cssText='font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:1px;color:var(--v23-cyan);margin:5px 0 0';hint.textContent='Choices can create memories, secrets, reputation shifts and future callbacks'; t.insertAdjacentElement('afterend',hint);}},20); return out;};
      UI._v23Patched=true;
    }
    if(window.App&&!App._v23Patched){
      const oldStart=App.startGame?.bind(App); if(oldStart)App.startGame=function(){const out=oldStart(); setTimeout(()=>{try{State.ensure(window.G); Memory.add(window.G,'life_begins_v23','Life Began',`${window.G.name} began a life that can now remember, hide secrets, form rivals and build a dynasty.`,'identity',5); UI23.installDom(); UI23.dashboard();}catch(e){console.warn(e);}},650); return out;};
      const oldLoad=App.loadGame?.bind(App); if(oldLoad)App.loadGame=function(){const out=oldLoad(); setTimeout(()=>{try{State.ensure(window.G); UI23.installDom(); UI23.dashboard();}catch(e){console.warn(e);}},350); return out;};
      App._v23Patched=true;
    }
    setTimeout(()=>{try{UI23.installDom(); State.ensure(window.G); UI23.dashboard();}catch(_){ }},450);
  }

  window.LifeSimV23={VERSION,State,Memory,Reputation,Moral,World,Ambition,RelationsPlus,Rivals,Secrets,Fate,Temptations,Procedural,UI:UI23,Dynasty,yearTick,patch};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch,{once:true}); else patch();
  window.addEventListener('load',patch);
})();
